#!/usr/bin/env python3
"""Audit and selectively clean macOS development caches."""

from __future__ import annotations

import argparse
import glob
import json
import os
import plistlib
import re
import shutil
import stat
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Set, Tuple


@dataclass(frozen=True)
class TargetSpec:
    key: str
    label: str
    category: str
    risk: str
    safe_to_delete: bool
    notes: str
    patterns: Sequence[str]


@dataclass
class ScanEntry:
    key: str
    label: str
    category: str
    risk: str
    safe_to_delete: bool
    notes: str
    path: Path
    source: str
    exists: bool
    size_bytes: int
    errors: int

    def to_json(self) -> Dict[str, object]:
        return {
            "key": self.key,
            "label": self.label,
            "category": self.category,
            "risk": self.risk,
            "safe_to_delete": self.safe_to_delete,
            "notes": self.notes,
            "path": str(self.path),
            "source": self.source,
            "exists": self.exists,
            "size_bytes": self.size_bytes,
            "size_human": format_size(self.size_bytes),
            "errors": self.errors,
        }


@dataclass
class OrphanEntry:
    bundle_id: str
    location: str
    path: Path
    size_bytes: int
    errors: int
    risk: str
    safe_to_delete: bool
    notes: str

    def to_json(self) -> Dict[str, object]:
        return {
            "bundle_id": self.bundle_id,
            "location": self.location,
            "path": str(self.path),
            "size_bytes": self.size_bytes,
            "size_human": format_size(self.size_bytes),
            "errors": self.errors,
            "risk": self.risk,
            "safe_to_delete": self.safe_to_delete,
            "notes": self.notes,
        }


STATIC_TARGETS: Sequence[TargetSpec] = (
    TargetSpec(
        key="gradle-caches",
        label="Gradle dependency cache",
        category="android",
        risk="low",
        safe_to_delete=True,
        notes="Downloaded artifacts; Gradle re-downloads them on demand.",
        patterns=("~/.gradle/caches",),
    ),
    TargetSpec(
        key="gradle-daemons",
        label="Gradle daemon data",
        category="android",
        risk="low",
        safe_to_delete=True,
        notes="Temporary daemon state. Closed daemons are safe to clear.",
        patterns=("~/.gradle/daemon",),
    ),
    TargetSpec(
        key="gradle-wrapper",
        label="Gradle wrapper distributions",
        category="android",
        risk="low",
        safe_to_delete=True,
        notes="Versioned Gradle binaries, re-downloaded by wrapper.",
        patterns=("~/.gradle/wrapper/dists",),
    ),
    TargetSpec(
        key="android-avd",
        label="Android emulator AVD images",
        category="android",
        risk="high",
        safe_to_delete=False,
        notes="Deletes emulator devices and snapshots.",
        patterns=("~/.android/avd",),
    ),
    TargetSpec(
        key="android-studio-caches",
        label="Android Studio caches",
        category="android",
        risk="medium",
        safe_to_delete=True,
        notes="Indices and caches are rebuildable but first reopen is slower.",
        patterns=("~/Library/Caches/Google/AndroidStudio*",),
    ),
    TargetSpec(
        key="android-sdk-temp",
        label="Android SDK temp cache",
        category="android",
        risk="low",
        safe_to_delete=True,
        notes="Temporary downloads under SDK root.",
        patterns=("~/Library/Android/sdk/.temp",),
    ),
    TargetSpec(
        key="cocoapods-cache",
        label="CocoaPods cache",
        category="ios",
        risk="low",
        safe_to_delete=True,
        notes="Pod tarballs/spec caches; re-fetched by CocoaPods.",
        patterns=("~/Library/Caches/CocoaPods",),
    ),
    TargetSpec(
        key="cocoapods-repos",
        label="CocoaPods specs repos",
        category="ios",
        risk="medium",
        safe_to_delete=True,
        notes="Specs clone can be re-cloned; next pod install is slower.",
        patterns=("~/.cocoapods/repos",),
    ),
    TargetSpec(
        key="xcode-derived-data",
        label="Xcode DerivedData",
        category="ios",
        risk="low",
        safe_to_delete=True,
        notes="Build artifacts and indexes; regenerated by Xcode.",
        patterns=("~/Library/Developer/Xcode/DerivedData",),
    ),
    TargetSpec(
        key="xcode-archives",
        label="Xcode Archives",
        category="ios",
        risk="high",
        safe_to_delete=False,
        notes="Contains archived builds used for symbolication/release history.",
        patterns=("~/Library/Developer/Xcode/Archives",),
    ),
    TargetSpec(
        key="ios-device-support",
        label="iOS Device Support",
        category="ios",
        risk="medium",
        safe_to_delete=True,
        notes="Device symbols can be re-generated/re-downloaded.",
        patterns=("~/Library/Developer/Xcode/iOS DeviceSupport",),
    ),
    TargetSpec(
        key="ios-simulators",
        label="CoreSimulator device data",
        category="ios",
        risk="high",
        safe_to_delete=False,
        notes="Deletes simulator apps/data; keep unless intentionally resetting.",
        patterns=("~/Library/Developer/CoreSimulator/Devices",),
    ),
    TargetSpec(
        key="npm-cache",
        label="npm cache",
        category="web",
        risk="low",
        safe_to_delete=True,
        notes="Package tarball cache; npm re-downloads as needed.",
        patterns=("~/.npm",),
    ),
    TargetSpec(
        key="yarn-cache",
        label="Yarn cache",
        category="web",
        risk="low",
        safe_to_delete=True,
        notes="Yarn package cache; recreated on next install.",
        patterns=("~/Library/Caches/Yarn", "~/.cache/yarn"),
    ),
    TargetSpec(
        key="pnpm-store",
        label="pnpm global store",
        category="web",
        risk="medium",
        safe_to_delete=True,
        notes="Store can be repopulated; next install may be slow.",
        patterns=("~/Library/pnpm/store", "~/.pnpm-store"),
    ),
    TargetSpec(
        key="homebrew-cache",
        label="Homebrew downloads cache",
        category="system",
        risk="low",
        safe_to_delete=True,
        notes="Downloaded bottles/tarballs; safe to clear.",
        patterns=("~/Library/Caches/Homebrew",),
    ),
)

HOME_DOTDIR_TARGETS: Sequence[TargetSpec] = (
    TargetSpec(
        key="home-dot-android",
        label="Home .android root",
        category="home-dotdir",
        risk="high",
        safe_to_delete=False,
        notes="Contains AVD/device state and Android tooling metadata.",
        patterns=("~/.android",),
    ),
    TargetSpec(
        key="home-dot-bun",
        label="Home .bun root",
        category="home-dotdir",
        risk="medium",
        safe_to_delete=False,
        notes="May include runtimes/config; review before deleting.",
        patterns=("~/.bun",),
    ),
    TargetSpec(
        key="home-dot-bun-cache",
        label="Bun install cache",
        category="home-dotdir",
        risk="low",
        safe_to_delete=True,
        notes="Bun cache can be rebuilt by reinstalling packages.",
        patterns=("~/.bun/install/cache",),
    ),
    TargetSpec(
        key="home-dot-cabal",
        label="Home .cabal root",
        category="home-dotdir",
        risk="medium",
        safe_to_delete=False,
        notes="May include user config and package metadata.",
        patterns=("~/.cabal",),
    ),
    TargetSpec(
        key="home-dot-bundle",
        label="Home .bundle root",
        category="home-dotdir",
        risk="medium",
        safe_to_delete=False,
        notes="Bundler settings can exist here; review manually.",
        patterns=("~/.bundle",),
    ),
    TargetSpec(
        key="home-dot-cargo",
        label="Home .cargo root",
        category="home-dotdir",
        risk="medium",
        safe_to_delete=False,
        notes="Contains Cargo toolchain config and caches.",
        patterns=("~/.cargo",),
    ),
    TargetSpec(
        key="home-dot-cargo-registry-cache",
        label="Cargo registry cache",
        category="home-dotdir",
        risk="low",
        safe_to_delete=True,
        notes="Downloaded crates; Cargo re-downloads when needed.",
        patterns=("~/.cargo/registry/cache", "~/.cargo/git/db"),
    ),
    TargetSpec(
        key="home-dot-claude",
        label="Home .claude root",
        category="home-dotdir",
        risk="high",
        safe_to_delete=False,
        notes="Likely contains assistant state/config; review first.",
        patterns=("~/.claude",),
    ),
    TargetSpec(
        key="home-dot-chelper",
        label="Home .chelper root",
        category="home-dotdir",
        risk="high",
        safe_to_delete=False,
        notes="Unknown tooling state; do not auto-clean.",
        patterns=("~/.chelper",),
    ),
    TargetSpec(
        key="home-dot-codex",
        label="Home .codex root",
        category="home-dotdir",
        risk="high",
        safe_to_delete=False,
        notes="Codex configuration and state.",
        patterns=("~/.codex",),
    ),
    TargetSpec(
        key="home-dot-codexbar",
        label="Home .codexbar root",
        category="home-dotdir",
        risk="high",
        safe_to_delete=False,
        notes="Potential app data/config; review manually.",
        patterns=("~/.codexbar",),
    ),
    TargetSpec(
        key="home-dot-composer",
        label="Home .composer root",
        category="home-dotdir",
        risk="medium",
        safe_to_delete=False,
        notes="May contain auth/config and cache.",
        patterns=("~/.composer",),
    ),
    TargetSpec(
        key="home-dot-composer-cache",
        label="Composer cache",
        category="home-dotdir",
        risk="low",
        safe_to_delete=True,
        notes="Composer package cache is rebuildable.",
        patterns=("~/.composer/cache",),
    ),
    TargetSpec(
        key="home-dot-copilot",
        label="Home .copilot root",
        category="home-dotdir",
        risk="high",
        safe_to_delete=False,
        notes="May include extension state and auth data.",
        patterns=("~/.copilot",),
    ),
    TargetSpec(
        key="home-dot-config",
        label="Home .config root",
        category="home-dotdir",
        risk="high",
        safe_to_delete=False,
        notes="General app/user configuration directory.",
        patterns=("~/.config",),
    ),
    TargetSpec(
        key="home-dot-cursor",
        label="Home .cursor root",
        category="home-dotdir",
        risk="high",
        safe_to_delete=False,
        notes="Cursor settings/state; do not auto-clean.",
        patterns=("~/.cursor",),
    ),
    TargetSpec(
        key="home-dot-dart-server",
        label="Home .dartServer",
        category="home-dotdir",
        risk="low",
        safe_to_delete=True,
        notes="Dart analysis server cache/state can be recreated.",
        patterns=("~/.dartServer",),
    ),
    TargetSpec(
        key="home-dot-dart-tool",
        label="Home .dart-tool",
        category="home-dotdir",
        risk="medium",
        safe_to_delete=False,
        notes="Potential user-level dart tool state.",
        patterns=("~/.dart-tool",),
    ),
    TargetSpec(
        key="home-dot-deno",
        label="Home .deno root",
        category="home-dotdir",
        risk="medium",
        safe_to_delete=False,
        notes="Contains runtime data and possibly user binaries.",
        patterns=("~/.deno",),
    ),
    TargetSpec(
        key="home-dot-deno-cache",
        label="Deno cache",
        category="home-dotdir",
        risk="low",
        safe_to_delete=True,
        notes="Deno deps/gen caches are rebuildable.",
        patterns=("~/.deno/deps", "~/.deno/gen"),
    ),
    TargetSpec(
        key="home-dot-docker",
        label="Home .docker root",
        category="home-dotdir",
        risk="high",
        safe_to_delete=False,
        notes="Docker client settings/contexts; manual review required.",
        patterns=("~/.docker",),
    ),
    TargetSpec(
        key="home-dot-expo",
        label="Home .expo root",
        category="home-dotdir",
        risk="medium",
        safe_to_delete=False,
        notes="May include credentials and app metadata.",
        patterns=("~/.expo",),
    ),
    TargetSpec(
        key="home-dot-gradle",
        label="Home .gradle root",
        category="home-dotdir",
        risk="medium",
        safe_to_delete=False,
        notes="Contains both cache and Gradle user state.",
        patterns=("~/.gradle",),
    ),
    TargetSpec(
        key="home-dot-hex",
        label="Home .hex root",
        category="home-dotdir",
        risk="medium",
        safe_to_delete=False,
        notes="Hex/rebar config and data.",
        patterns=("~/.hex",),
    ),
    TargetSpec(
        key="home-dot-hex-packages",
        label="Hex package cache",
        category="home-dotdir",
        risk="low",
        safe_to_delete=True,
        notes="Cached Hex packages can be re-fetched.",
        patterns=("~/.hex/packages",),
    ),
    TargetSpec(
        key="home-dot-ipython",
        label="Home .ipython root",
        category="home-dotdir",
        risk="medium",
        safe_to_delete=False,
        notes="Contains history/profile settings.",
        patterns=("~/.ipython",),
    ),
    TargetSpec(
        key="home-dot-local",
        label="Home .local root",
        category="home-dotdir",
        risk="high",
        safe_to_delete=False,
        notes="Often contains user binaries and app state.",
        patterns=("~/.local",),
    ),
    TargetSpec(
        key="home-dot-yarn",
        label="Home .yarn root",
        category="home-dotdir",
        risk="medium",
        safe_to_delete=False,
        notes="May contain releases/config and cache.",
        patterns=("~/.yarn",),
    ),
    TargetSpec(
        key="home-dot-yarn-cache",
        label="Home .yarn cache",
        category="home-dotdir",
        risk="low",
        safe_to_delete=True,
        notes="Yarn cache can be recreated by installs.",
        patterns=("~/.yarn/cache",),
    ),
)

PROJECT_DIR_POLICIES: Dict[str, Dict[str, object]] = {
    "node_modules": {
        "key": "project-node-modules",
        "risk": "low",
        "safe_to_delete": True,
        "notes": "Rebuilt by package manager install.",
    },
    "Pods": {
        "key": "project-pods",
        "risk": "medium",
        "safe_to_delete": True,
        "notes": "Rebuilt by pod install.",
    },
    ".gradle": {
        "key": "project-gradle",
        "risk": "medium",
        "safe_to_delete": True,
        "notes": "Project-local Gradle cache; rebuilds/downloads on next build.",
    },
    "build": {
        "key": "project-build",
        "risk": "low",
        "safe_to_delete": True,
        "notes": "Generated build outputs.",
    },
    "dist": {
        "key": "project-dist",
        "risk": "low",
        "safe_to_delete": True,
        "notes": "Generated distribution outputs.",
    },
    ".next": {
        "key": "project-next",
        "risk": "low",
        "safe_to_delete": True,
        "notes": "Next.js cache/build artifacts.",
    },
    ".turbo": {
        "key": "project-turbo",
        "risk": "low",
        "safe_to_delete": True,
        "notes": "Turborepo local cache.",
    },
    ".dart_tool": {
        "key": "project-dart-tool",
        "risk": "low",
        "safe_to_delete": True,
        "notes": "Dart/Flutter generated tool state.",
    },
    ".expo": {
        "key": "project-expo",
        "risk": "low",
        "safe_to_delete": True,
        "notes": "Expo local cache/state.",
    },
    ".parcel-cache": {
        "key": "project-parcel-cache",
        "risk": "low",
        "safe_to_delete": True,
        "notes": "Parcel bundler cache.",
    },
    ".vite": {
        "key": "project-vite-cache",
        "risk": "low",
        "safe_to_delete": True,
        "notes": "Vite cache output.",
    },
}

SKIP_WALK_DIRS: Set[str] = {
    ".git",
    ".hg",
    ".svn",
    ".idea",
    ".vscode",
    ".Trash",
}

RISK_ORDER = {"low": 0, "medium": 1, "high": 2, "unknown": 3}
BUNDLE_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9.-]*\.[A-Za-z0-9.-]+$")
RISK_CONFIRM_TOKEN = "DELETE_HIGH_RISK"
ORPHAN_CONFIRM_TOKEN = "DELETE_ORPHAN_APP_DATA"
ORPHAN_SCAN_PATTERNS: Sequence[Tuple[str, str]] = (
    ("application-support", "~/Library/Application Support/*"),
    ("caches", "~/Library/Caches/*"),
    ("containers", "~/Library/Containers/*"),
    ("group-containers", "~/Library/Group Containers/*"),
    ("http-storages", "~/Library/HTTPStorages/*"),
    ("saved-state", "~/Library/Saved Application State/*"),
    ("preferences", "~/Library/Preferences/*.plist"),
    ("logs", "~/Library/Logs/*"),
)
EXCLUDED_ORPHAN_BUNDLE_PREFIXES: Sequence[str] = ("com.apple.",)


def format_size(size_bytes: int) -> str:
    if size_bytes < 1024:
        return f"{size_bytes} B"
    units = ("KB", "MB", "GB", "TB")
    value = float(size_bytes)
    for unit in units:
        value /= 1024.0
        if value < 1024.0 or unit == units[-1]:
            return f"{value:.2f} {unit}"
    return f"{value:.2f} TB"


def expand_patterns(patterns: Sequence[str]) -> List[Path]:
    paths: List[Path] = []
    for raw in patterns:
        expanded = os.path.expanduser(raw)
        matches = glob.glob(expanded)
        if matches:
            paths.extend(Path(match) for match in matches)
            continue
        if glob.has_magic(expanded):
            continue
        paths.append(Path(expanded))
    deduped: List[Path] = []
    seen: Set[str] = set()
    for path in paths:
        key = str(path.resolve(strict=False))
        if key not in seen:
            seen.add(key)
            deduped.append(path)
    return deduped


def path_size(path: Path) -> tuple[int, int]:
    if not path.exists():
        return 0, 0

    try:
        if path.is_symlink():
            return 0, 0
        if path.is_file():
            return path.stat().st_size, 0
    except OSError:
        return 0, 1

    total = 0
    errors = 0
    stack: List[Path] = [path]
    while stack:
        current = stack.pop()
        try:
            with os.scandir(current) as scan:
                for entry in scan:
                    try:
                        if entry.is_symlink():
                            continue
                        mode = entry.stat(follow_symlinks=False).st_mode
                        if stat.S_ISDIR(mode):
                            stack.append(Path(entry.path))
                        elif stat.S_ISREG(mode):
                            total += entry.stat(follow_symlinks=False).st_size
                    except OSError:
                        errors += 1
        except OSError:
            errors += 1
    return total, errors


def read_bundle_identifier(app_path: Path) -> Optional[str]:
    info_plist = app_path / "Contents" / "Info.plist"
    if not info_plist.exists():
        return None
    try:
        with info_plist.open("rb") as handle:
            payload = plistlib.load(handle)
    except Exception:  # noqa: BLE001
        return None
    bundle_id = payload.get("CFBundleIdentifier")
    if isinstance(bundle_id, str) and bundle_id.strip():
        return bundle_id.strip()
    return None


def default_app_roots() -> List[Path]:
    roots = [
        Path("/Applications"),
        Path("/System/Applications"),
        Path("/System/Library/CoreServices"),
        Path.home() / "Applications",
    ]
    roots.extend(Path(path) for path in glob.glob("/Volumes/*/Applications"))
    deduped: List[Path] = []
    seen: Set[str] = set()
    for root in roots:
        canonical = str(root.resolve(strict=False))
        if canonical in seen:
            continue
        seen.add(canonical)
        deduped.append(root)
    return deduped


def collect_installed_bundle_ids(extra_roots: Sequence[Path] = ()) -> Set[str]:
    roots = default_app_roots() + [root.expanduser() for root in extra_roots]
    deduped_roots: List[Path] = []
    seen_roots: Set[str] = set()
    for root in roots:
        canonical = str(root.resolve(strict=False))
        if canonical in seen_roots:
            continue
        seen_roots.add(canonical)
        deduped_roots.append(root)

    bundle_ids: Set[str] = set()
    for root in deduped_roots:
        if not root.exists() or not root.is_dir():
            continue
        if root.name.endswith(".app"):
            bundle_id = read_bundle_identifier(root)
            if bundle_id:
                bundle_ids.add(bundle_id)
            continue
        for current_root, dirnames, _ in os.walk(root, topdown=True):
            for dirname in list(dirnames):
                if not dirname.endswith(".app"):
                    continue
                app_path = Path(current_root) / dirname
                bundle_id = read_bundle_identifier(app_path)
                if bundle_id:
                    bundle_ids.add(bundle_id)
                dirnames.remove(dirname)
    return bundle_ids


def bundle_id_candidates(location: str, path: Path) -> List[str]:
    if location == "preferences":
        raw = path.stem
    elif location == "saved-state":
        raw = path.name[:-11] if path.name.endswith(".savedState") else path.name
    else:
        raw = path.name

    candidates: List[str] = []
    if raw.startswith("group."):
        candidates.append(raw[len("group."):])
    candidates.append(raw)

    valid: List[str] = []
    seen: Set[str] = set()
    for candidate in candidates:
        candidate = candidate.strip()
        if candidate in seen:
            continue
        if not BUNDLE_ID_RE.match(candidate):
            continue
        seen.add(candidate)
        valid.append(candidate)
    return valid


def detect_orphan_app_data(extra_app_roots: Sequence[Path] = ()) -> List[OrphanEntry]:
    installed_bundle_ids = collect_installed_bundle_ids(extra_roots=extra_app_roots)
    entries: List[OrphanEntry] = []
    for location, pattern in ORPHAN_SCAN_PATTERNS:
        for path in expand_patterns((pattern,)):
            if not path.exists():
                continue
            candidates = bundle_id_candidates(location=location, path=path)
            if not candidates:
                continue
            if any(
                candidate.startswith(prefix)
                for candidate in candidates
                for prefix in EXCLUDED_ORPHAN_BUNDLE_PREFIXES
            ):
                continue
            if any(candidate in installed_bundle_ids for candidate in candidates):
                continue
            size_bytes, errors = path_size(path)
            entries.append(
                OrphanEntry(
                    bundle_id=candidates[0],
                    location=location,
                    path=path,
                    size_bytes=size_bytes,
                    errors=errors,
                    risk="medium",
                    safe_to_delete=True,
                    notes=(
                        "No installed app bundle matched this bundle identifier in "
                        "standard app locations (/Applications, /System/Applications, "
                        "/System/Library/CoreServices, ~/Applications)."
                    ),
                )
            )
    entries.sort(key=lambda entry: (-entry.size_bytes, entry.bundle_id, str(entry.path)))
    return entries


def orphan_entries_to_scan_entries(entries: Sequence[OrphanEntry]) -> List[ScanEntry]:
    converted: List[ScanEntry] = []
    for entry in entries:
        converted.append(
            ScanEntry(
                key="orphan-app-data",
                label=f"Orphan app data: {entry.bundle_id}",
                category="orphan",
                risk=entry.risk,
                safe_to_delete=entry.safe_to_delete,
                notes=entry.notes,
                path=entry.path,
                source="orphan",
                exists=entry.path.exists(),
                size_bytes=entry.size_bytes,
                errors=entry.errors,
            )
        )
    return converted


def scan_static_targets(include_missing: bool) -> List[ScanEntry]:
    entries: List[ScanEntry] = []
    for target in STATIC_TARGETS:
        for path in expand_patterns(target.patterns):
            exists = path.exists()
            if not exists and not include_missing:
                continue
            size_bytes, errors = path_size(path) if exists else (0, 0)
            entries.append(
                ScanEntry(
                    key=target.key,
                    label=target.label,
                    category=target.category,
                    risk=target.risk,
                    safe_to_delete=target.safe_to_delete,
                    notes=target.notes,
                    path=path,
                    source="static",
                    exists=exists,
                    size_bytes=size_bytes,
                    errors=errors,
                )
            )
    return entries


def scan_home_dotdir_targets(include_missing: bool) -> List[ScanEntry]:
    entries: List[ScanEntry] = []
    for target in HOME_DOTDIR_TARGETS:
        for path in expand_patterns(target.patterns):
            exists = path.exists()
            if not exists and not include_missing:
                continue
            size_bytes, errors = path_size(path) if exists else (0, 0)
            entries.append(
                ScanEntry(
                    key=target.key,
                    label=target.label,
                    category=target.category,
                    risk=target.risk,
                    safe_to_delete=target.safe_to_delete,
                    notes=target.notes,
                    path=path,
                    source="home-dotdir",
                    exists=exists,
                    size_bytes=size_bytes,
                    errors=errors,
                )
            )
    return entries


def scan_project_targets(project_roots: Sequence[Path]) -> List[ScanEntry]:
    entries: List[ScanEntry] = []
    for root in project_roots:
        normalized_root = root.expanduser().resolve()
        if not normalized_root.exists() or not normalized_root.is_dir():
            print(f"[WARN] Project root not found or not a directory: {normalized_root}")
            continue

        for current_root, dirnames, _ in os.walk(normalized_root, topdown=True):
            dirnames[:] = [d for d in dirnames if d not in SKIP_WALK_DIRS]
            matched: List[str] = []
            for dirname in list(dirnames):
                if dirname not in PROJECT_DIR_POLICIES:
                    continue
                matched.append(dirname)
                dirnames.remove(dirname)

            for dirname in matched:
                found = Path(current_root) / dirname
                policy = PROJECT_DIR_POLICIES[dirname]
                size_bytes, errors = path_size(found)
                entries.append(
                    ScanEntry(
                        key=str(policy["key"]),
                        label=f"Project cache: {dirname}",
                        category="project",
                        risk=str(policy["risk"]),
                        safe_to_delete=bool(policy["safe_to_delete"]),
                        notes=str(policy["notes"]),
                        path=found,
                        source="project",
                        exists=True,
                        size_bytes=size_bytes,
                        errors=errors,
                    )
                )
    return entries


def scan_all(
    project_roots: Sequence[Path],
    include_missing: bool,
    include_home_dotdirs: bool,
    include_orphans: bool,
    orphan_app_roots: Sequence[Path] = (),
) -> List[ScanEntry]:
    entries = scan_static_targets(include_missing=include_missing)
    if include_home_dotdirs:
        entries.extend(scan_home_dotdir_targets(include_missing=include_missing))
    if project_roots:
        entries.extend(scan_project_targets(project_roots=project_roots))
    if include_orphans:
        entries.extend(
            orphan_entries_to_scan_entries(detect_orphan_app_data(extra_app_roots=orphan_app_roots))
        )
    entries.sort(
        key=lambda item: (
            -item.size_bytes,
            RISK_ORDER.get(item.risk, 99),
            str(item.path),
        )
    )
    return entries


def print_report(entries: Sequence[ScanEntry], min_size_bytes: int) -> None:
    filtered = [item for item in entries if item.size_bytes >= min_size_bytes]
    if not filtered:
        print("No matching cache targets found.")
        return

    key_width = max(6, max(len(item.key) for item in filtered))
    risk_width = max(4, max(len(item.risk) for item in filtered))
    safe_width = 4
    print(
        f"{'SIZE':>10}  {'RISK':<{risk_width}}  {'SAFE':<{safe_width}}  {'KEY':<{key_width}}  PATH"
    )
    print("-" * 120)
    for item in filtered:
        safe = "yes" if item.safe_to_delete else "no"
        print(
            f"{format_size(item.size_bytes):>10}  {item.risk:<{risk_width}}  {safe:<{safe_width}}  "
            f"{item.key:<{key_width}}  {item.path}"
        )
        print(f"{'':>10}  {'':<{risk_width}}  {'':<{safe_width}}  {'':<{key_width}}  note: {item.notes}")
        if item.errors:
            print(
                f"{'':>10}  {'':<{risk_width}}  {'':<{safe_width}}  {'':<{key_width}}  "
                f"warn: size scan had {item.errors} permission/read errors"
            )


def write_json(entries: Sequence[ScanEntry], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    payload = [entry.to_json() for entry in entries]
    output_path.write_text(json.dumps(payload, indent=2))
    print(f"Wrote JSON report: {output_path}")


def print_orphan_report(entries: Sequence[OrphanEntry], min_size_bytes: int) -> None:
    filtered = [item for item in entries if item.size_bytes >= min_size_bytes]
    if not filtered:
        print("No orphan app data found.")
        return
    bundle_width = max(10, max(len(item.bundle_id) for item in filtered))
    loc_width = max(8, max(len(item.location) for item in filtered))
    print(f"{'SIZE':>10}  {'BUNDLE_ID':<{bundle_width}}  {'LOCATION':<{loc_width}}  PATH")
    print("-" * 120)
    for item in filtered:
        print(
            f"{format_size(item.size_bytes):>10}  "
            f"{item.bundle_id:<{bundle_width}}  {item.location:<{loc_width}}  {item.path}"
        )
        print(
            f"{'':>10}  {'':<{bundle_width}}  {'':<{loc_width}}  "
            f"note: {item.notes}"
        )
        if item.errors:
            print(
                f"{'':>10}  {'':<{bundle_width}}  {'':<{loc_width}}  "
                f"warn: size scan had {item.errors} permission/read errors"
            )


def write_orphan_json(entries: Sequence[OrphanEntry], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    payload = [entry.to_json() for entry in entries]
    output_path.write_text(json.dumps(payload, indent=2))
    print(f"Wrote orphan JSON report: {output_path}")


def build_known_path_index() -> Dict[str, TargetSpec]:
    index: Dict[str, TargetSpec] = {}
    for target in list(STATIC_TARGETS) + list(HOME_DOTDIR_TARGETS):
        for path in expand_patterns(target.patterns):
            index[str(path.resolve(strict=False))] = target
    return index


def total_unique_size(entries: Sequence[ScanEntry]) -> int:
    ordered = sorted(
        entries,
        key=lambda item: (
            len(item.path.resolve(strict=False).parts),
            str(item.path.resolve(strict=False)),
        ),
    )
    selected_paths: List[Path] = []
    total = 0
    for entry in ordered:
        resolved = entry.path.resolve(strict=False)
        if any(is_relative_to(resolved, parent) for parent in selected_paths):
            continue
        selected_paths.append(resolved)
        total += entry.size_bytes
    return total


def is_relative_to(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
        return True
    except ValueError:
        return False


def prune_nested_entries(entries: Sequence[ScanEntry]) -> List[ScanEntry]:
    resolved = [item.path.resolve(strict=False) for item in entries]
    keep_flags = [True] * len(entries)

    for i, path_i in enumerate(resolved):
        for j, path_j in enumerate(resolved):
            if i == j:
                continue
            if path_i == path_j:
                continue
            if is_relative_to(path_i, path_j):
                keep_flags[i] = False
                print(
                    "[INFO] Skipping nested selection because parent path is also selected: "
                    f"{entries[i].path} (parent: {entries[j].path})"
                )
                break

    return [item for item, keep in zip(entries, keep_flags) if keep]


def select_entries(
    entries: Sequence[ScanEntry],
    selected_keys: Sequence[str],
    selected_paths: Sequence[str],
    allow_unknown_paths: bool,
    static_index: Dict[str, TargetSpec],
) -> List[ScanEntry]:
    selected: List[ScanEntry] = []

    for key in selected_keys:
        matched = [item for item in entries if item.key == key]
        if not matched:
            print(f"[WARN] No scan entries found for key: {key}")
            continue
        selected.extend(matched)

    known_by_path: Dict[str, ScanEntry] = {
        str(item.path.resolve(strict=False)): item for item in entries
    }
    for raw_path in selected_paths:
        path = Path(os.path.expanduser(raw_path)).resolve(strict=False)
        canonical = str(path)
        known = known_by_path.get(canonical)
        if known:
            selected.append(known)
            continue
        static_target = static_index.get(canonical)
        if static_target:
            size_bytes, errors = path_size(path)
            selected.append(
                ScanEntry(
                    key=static_target.key,
                    label=static_target.label,
                    category=static_target.category,
                    risk=static_target.risk,
                    safe_to_delete=static_target.safe_to_delete,
                    notes=static_target.notes,
                    path=path,
                    source="static-path",
                    exists=path.exists(),
                    size_bytes=size_bytes,
                    errors=errors,
                )
            )
            continue
        project_policy = PROJECT_DIR_POLICIES.get(path.name)
        if project_policy and path.exists():
            size_bytes, errors = path_size(path)
            selected.append(
                ScanEntry(
                    key=str(project_policy["key"]),
                    label=f"Project cache: {path.name}",
                    category="project",
                    risk=str(project_policy["risk"]),
                    safe_to_delete=bool(project_policy["safe_to_delete"]),
                    notes=str(project_policy["notes"]),
                    path=path,
                    source="path-hint",
                    exists=True,
                    size_bytes=size_bytes,
                    errors=errors,
                )
            )
            continue
        if not allow_unknown_paths:
            print(
                "[WARN] Skipping unknown path (not present in current scan): "
                f"{canonical}. Use --allow-unknown-paths to override."
            )
            continue
        size_bytes, errors = path_size(path)
        selected.append(
            ScanEntry(
                key="custom-path",
                label="Custom path",
                category="custom",
                risk="unknown",
                safe_to_delete=False,
                notes="User-provided path outside scanned targets.",
                path=path,
                source="custom",
                exists=path.exists(),
                size_bytes=size_bytes,
                errors=errors,
            )
        )

    deduped: List[ScanEntry] = []
    seen: Set[str] = set()
    for item in selected:
        canonical = str(item.path.resolve(strict=False))
        if canonical in seen:
            continue
        seen.add(canonical)
        deduped.append(item)
    return prune_nested_entries(deduped)


def is_protected(path: Path) -> bool:
    resolved = path.resolve(strict=False)
    home = Path.home().resolve(strict=False)
    protected = {
        Path("/"),
        home,
        Path("/System"),
        Path("/Applications"),
        Path("/Users"),
        Path("/Volumes"),
        Path("/Library"),
    }
    return resolved in protected


def delete_path(path: Path) -> tuple[bool, str, int]:
    resolved = path.resolve(strict=False)
    if is_protected(resolved):
        return False, "refused: protected path", 0
    if not resolved.exists():
        return True, "skipped: already missing", 0

    reclaimable_size, _ = path_size(resolved)

    try:
        if resolved.is_symlink() or resolved.is_file():
            resolved.unlink()
            return True, "deleted file/symlink", reclaimable_size
        if resolved.is_dir():
            shutil.rmtree(resolved)
            return True, "deleted directory tree", reclaimable_size
        return False, "unsupported path type", 0
    except Exception as exc:  # noqa: BLE001
        return False, f"delete failed: {exc}", 0


def needs_strict_risk_confirmation(entries: Sequence[ScanEntry]) -> bool:
    for item in entries:
        if item.risk in {"high", "unknown"}:
            return True
        if not item.safe_to_delete:
            return True
    return False


def command_scan(args: argparse.Namespace) -> int:
    project_roots = [Path(item) for item in args.project_root]
    orphan_app_roots = [Path(item) for item in args.app_root]
    entries = scan_all(
        project_roots=project_roots,
        include_missing=args.include_missing,
        include_home_dotdirs=args.include_home_dotdirs,
        include_orphans=args.include_orphans,
        orphan_app_roots=orphan_app_roots,
    )
    min_size_bytes = int(args.min_size_mb * 1024 * 1024)

    print_report(entries=entries, min_size_bytes=min_size_bytes)
    filtered = [item for item in entries if item.size_bytes >= min_size_bytes]
    total_bytes = total_unique_size(filtered)
    print(f"\nTotal in report: {format_size(total_bytes)}")

    if args.json_out:
        write_json(entries=entries, output_path=Path(args.json_out).expanduser())
    return 0


def command_clean(args: argparse.Namespace) -> int:
    if not args.key and not args.path:
        print("Provide at least one --key or --path for cleanup.")
        return 2
    if args.apply and not args.yes:
        print("Real deletion requires --apply plus --yes.")
        return 2

    entries: List[ScanEntry] = []
    if args.key:
        project_roots = [Path(item) for item in args.project_root]
        entries = scan_all(
            project_roots=project_roots,
            include_missing=False,
            include_home_dotdirs=args.include_home_dotdirs,
            include_orphans=False,
        )
    static_index = build_known_path_index()
    selected = select_entries(
        entries=entries,
        selected_keys=args.key,
        selected_paths=args.path,
        allow_unknown_paths=args.allow_unknown_paths,
        static_index=static_index,
    )
    if not selected:
        print("No cleanup targets selected after filtering.")
        return 2

    print("Selected cleanup targets:")
    for item in selected:
        safe = "yes" if item.safe_to_delete else "no"
        print(
            f"- {item.path} | size={format_size(item.size_bytes)} | risk={item.risk} | safe={safe} | key={item.key}"
        )
        print(f"  note: {item.notes}")

    total_size = sum(item.size_bytes for item in selected)
    print(f"\nEstimated reclaimable space: {format_size(total_size)}")

    requires_risk_token = needs_strict_risk_confirmation(selected)
    if requires_risk_token:
        print(
            f"Selected targets include high-risk/non-safe paths. Strict token required for apply mode: {RISK_CONFIRM_TOKEN}"
        )

    if not args.apply:
        print(
            "\nDry run only. Re-run with --apply --yes to actually delete the selected targets."
        )
        return 0
    if requires_risk_token and args.confirm_risk != RISK_CONFIRM_TOKEN:
        print(
            "Refusing apply mode for high-risk/non-safe targets without strict confirmation token. "
            f"Use --confirm-risk {RISK_CONFIRM_TOKEN}"
        )
        return 2

    reclaimed = 0
    failures = 0
    for item in selected:
        ok, message, reclaimed_bytes = delete_path(item.path)
        if ok:
            reclaimed += reclaimed_bytes
            print(f"[OK] {item.path}: {message}")
        else:
            failures += 1
            print(f"[ERR] {item.path}: {message}")

    print(f"\nReclaimed estimate: {format_size(reclaimed)}")
    if failures:
        print(f"Cleanup finished with {failures} failure(s).")
        return 1

    print("Cleanup finished successfully.")
    return 0


def command_scan_orphans(args: argparse.Namespace) -> int:
    app_roots = [Path(item) for item in args.app_root]
    entries = detect_orphan_app_data(extra_app_roots=app_roots)
    min_size_bytes = int(args.min_size_mb * 1024 * 1024)
    print_orphan_report(entries=entries, min_size_bytes=min_size_bytes)
    total_bytes = sum(item.size_bytes for item in entries if item.size_bytes >= min_size_bytes)
    print(f"\nTotal orphan data in report: {format_size(total_bytes)}")
    if args.json_out:
        write_orphan_json(entries=entries, output_path=Path(args.json_out).expanduser())
    return 0


def command_clean_orphans(args: argparse.Namespace) -> int:
    if not args.bundle_id and not args.path and not args.all:
        print("Choose orphan targets with --bundle-id/--path, or use --all.")
        return 2
    if args.apply and not args.yes:
        print("Real deletion requires --apply plus --yes.")
        return 2
    if args.apply and args.confirm_orphans != ORPHAN_CONFIRM_TOKEN:
        print(
            "Refusing orphan cleanup without strict confirmation token. "
            f"Use --confirm-orphans {ORPHAN_CONFIRM_TOKEN}"
        )
        return 2

    app_roots = [Path(item) for item in args.app_root]
    entries = detect_orphan_app_data(extra_app_roots=app_roots)
    min_size_bytes = int(args.min_size_mb * 1024 * 1024)
    filtered = [item for item in entries if item.size_bytes >= min_size_bytes]

    bundle_filter = set(args.bundle_id)
    path_filter = {
        str(Path(os.path.expanduser(raw_path)).resolve(strict=False)) for raw_path in args.path
    }

    selected: List[ScanEntry] = []
    for item in filtered:
        selected_by_bundle = bool(bundle_filter) and item.bundle_id in bundle_filter
        selected_by_path = bool(path_filter) and str(item.path.resolve(strict=False)) in path_filter
        selected_by_all = args.all
        if not (selected_by_bundle or selected_by_path or selected_by_all):
            continue
        selected.append(
            ScanEntry(
                key="orphan-app-data",
                label=f"Orphan app data: {item.bundle_id}",
                category="orphan",
                risk=item.risk,
                safe_to_delete=item.safe_to_delete,
                notes=item.notes,
                path=item.path,
                source="orphan",
                exists=item.path.exists(),
                size_bytes=item.size_bytes,
                errors=item.errors,
            )
        )

    selected = prune_nested_entries(selected)
    if not selected:
        print("No orphan cleanup targets matched your filters.")
        return 2

    print("Selected orphan cleanup targets:")
    for item in selected:
        print(
            f"- {item.path} | size={format_size(item.size_bytes)} | risk={item.risk} | safe=yes | key={item.key}"
        )
        print(f"  note: {item.notes}")
    total_size = sum(item.size_bytes for item in selected)
    print(f"\nEstimated reclaimable orphan space: {format_size(total_size)}")

    if not args.apply:
        print(
            "\nDry run only. Re-run with --apply --yes "
            f"--confirm-orphans {ORPHAN_CONFIRM_TOKEN} to actually delete."
        )
        return 0

    reclaimed = 0
    failures = 0
    for item in selected:
        ok, message, reclaimed_bytes = delete_path(item.path)
        if ok:
            reclaimed += reclaimed_bytes
            print(f"[OK] {item.path}: {message}")
        else:
            failures += 1
            print(f"[ERR] {item.path}: {message}")

    print(f"\nReclaimed orphan estimate: {format_size(reclaimed)}")
    if failures:
        print(f"Orphan cleanup finished with {failures} failure(s).")
        return 1
    print("Orphan cleanup finished successfully.")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Analyze and selectively clean macOS development caches."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    scan_parser = subparsers.add_parser("scan", help="Scan known cache locations.")
    scan_parser.add_argument(
        "--project-root",
        action="append",
        default=[],
        help="Project root to scan for node_modules/build-like folders (repeatable).",
    )
    scan_parser.add_argument(
        "--min-size-mb",
        type=float,
        default=0.0,
        help="Show entries larger than this size in MB (default: 0).",
    )
    scan_parser.add_argument(
        "--include-missing",
        action="store_true",
        help="Include targets that are configured but currently missing.",
    )
    scan_parser.add_argument(
        "--json-out",
        help="Write full scan output to this JSON file.",
    )
    scan_parser.add_argument(
        "--include-home-dotdirs",
        action="store_true",
        help="Scan additional home dot-directories with risk tags.",
    )
    scan_parser.add_argument(
        "--include-orphans",
        action="store_true",
        help="Include orphan app-data candidates in the general report.",
    )
    scan_parser.add_argument(
        "--app-root",
        action="append",
        default=[],
        help="Additional application root to inspect for installed bundle IDs (repeatable).",
    )
    scan_parser.set_defaults(handler=command_scan)

    clean_parser = subparsers.add_parser("clean", help="Delete selected cache paths.")
    clean_parser.add_argument(
        "--project-root",
        action="append",
        default=[],
        help="Project root to include in the scan before selecting targets.",
    )
    clean_parser.add_argument(
        "--key",
        action="append",
        default=[],
        help="Cleanup key from scan output (repeatable).",
    )
    clean_parser.add_argument(
        "--path",
        action="append",
        default=[],
        help="Exact path from scan output to delete (repeatable).",
    )
    clean_parser.add_argument(
        "--allow-unknown-paths",
        action="store_true",
        help="Allow deleting custom paths not present in current scan output.",
    )
    clean_parser.add_argument(
        "--apply",
        action="store_true",
        help="Actually delete selected targets. Without this flag, run dry-run only.",
    )
    clean_parser.add_argument(
        "--yes",
        action="store_true",
        help="Required with --apply to confirm destructive action.",
    )
    clean_parser.add_argument(
        "--confirm-risk",
        help=f"Strict token for high-risk/non-safe cleanup: {RISK_CONFIRM_TOKEN}",
    )
    clean_parser.add_argument(
        "--include-home-dotdirs",
        action="store_true",
        help="Allow --key selection from home dot-directory targets.",
    )
    clean_parser.set_defaults(handler=command_clean)

    scan_orphan_parser = subparsers.add_parser(
        "scan-orphans",
        help="Detect orphan app data (app removed but data remains).",
    )
    scan_orphan_parser.add_argument(
        "--min-size-mb",
        type=float,
        default=0.0,
        help="Show entries larger than this size in MB (default: 0).",
    )
    scan_orphan_parser.add_argument(
        "--json-out",
        help="Write orphan scan output to this JSON file.",
    )
    scan_orphan_parser.add_argument(
        "--app-root",
        action="append",
        default=[],
        help="Additional application root to inspect for installed bundle IDs (repeatable).",
    )
    scan_orphan_parser.set_defaults(handler=command_scan_orphans)

    clean_orphan_parser = subparsers.add_parser(
        "clean-orphans",
        help="Delete selected orphan app data paths with strict confirmation.",
    )
    clean_orphan_parser.add_argument(
        "--bundle-id",
        action="append",
        default=[],
        help="Bundle ID from scan-orphans output (repeatable).",
    )
    clean_orphan_parser.add_argument(
        "--path",
        action="append",
        default=[],
        help="Exact path from scan-orphans output (repeatable).",
    )
    clean_orphan_parser.add_argument(
        "--all",
        action="store_true",
        help="Select all detected orphan entries (use carefully).",
    )
    clean_orphan_parser.add_argument(
        "--min-size-mb",
        type=float,
        default=0.0,
        help="Only include orphan entries larger than this size in MB.",
    )
    clean_orphan_parser.add_argument(
        "--apply",
        action="store_true",
        help="Actually delete selected orphan targets. Without this flag, dry-run only.",
    )
    clean_orphan_parser.add_argument(
        "--yes",
        action="store_true",
        help="Required with --apply to confirm destructive action.",
    )
    clean_orphan_parser.add_argument(
        "--confirm-orphans",
        help=f"Strict token required for orphan cleanup apply mode: {ORPHAN_CONFIRM_TOKEN}",
    )
    clean_orphan_parser.add_argument(
        "--app-root",
        action="append",
        default=[],
        help="Additional application root to inspect for installed bundle IDs (repeatable).",
    )
    clean_orphan_parser.set_defaults(handler=command_clean_orphans)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return int(args.handler(args))


if __name__ == "__main__":
    raise SystemExit(main())
